### ISSUE TITLE
Improved Spanish translation

### ISSUE THREAD

**Issue by quieneslatern** [academico-sis/academico#240]
revised sp.json
I change 
-classes => clases
-per => por
I don't know when use the phrases:
-Students to count in year total
-Year Students
In french translation i don't found this phrases.

**Comment by thdebay** [comment]
The phrases you mentioned (`Students to count in year total` and `Year Students`) are used in ExternalCourseCrudController. These courses generally do not receive enrolments, because the external students don't have individual accounts on the platform. We use these fields to manually specify the number of students to take into account in the external courses report.
